DELETE http://localhost:4000/delete/390725
###
DELETE http://localhost:4000/delete/SW%202021
###
GET http://localhost:4000/objects

###
GET http://localhost:4000/objects/2024%20EY3

###
PUT http://localhost:4000/update/2025%20FU5
Content-Type: application/json

{
  "date": "2025-06-01 12:00",
  "dist": "0.035",
  "relativeVelocity": "7.5"
}

###
POST http://localhost:4000/create
Content-Type: application/json

{
  "name": "kosteg", 
  "date": "2025-06-03 12:00",
  "dist": "0.1",
  "relativeVelocity": "10"
}
